name: Testing project code
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run valid test
        id: test1
        continue-on-error: true
        run: python -m unittest testValid.py
      - name: Run min test
        id: test2
        continue-on-error: true
        run: python -m unittest testMin.py
      - name: Run max test
        id: test3
        continue-on-error: true
        run: python -m unittest testMax.py
      - name: Run sum test
        id: test4
        continue-on-error: true
        run: python -m unittest testSum.py
      - name: Run multiply test
        id: test5
        continue-on-error: true
        run: python -m unittest testMultiply.py
      - name: Run speed tests
        id: test6
        continue-on-error: true
        run: python -m unittest speedTests.py
      - name: Setup veriables
        run: |
          if [ "${{ steps.test1.outcome }}" = "success" ]; then
            test1="пройден"
          else
            test1="провален"
          fi
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} внёс изменения в репозиторий:
            Комментарий: ${{ github.event.commits[0].message }}
            
            Результаты тестов:
            1) Тест на корректное считывание: <b><u>${{ env.test1 }}</u></b>
            2) Тест на корректное вычисление минимума: <b><u>${{ steps.test2.outcome }}</u></b>
            3) Тест на корректное вычисление максимума: <b><u>${{ steps.test3.outcome }}</u></b>
            4) Тест на корректное вычисление суммы: <b><u>${{ steps.test4.outcome }}</u></b>
            5) Тест на корректное вычисление произведения: <b><u>${{ steps.test5.outcome }}</u></b>
            6) Тесты на скорость: <b><u>${{ steps.test6.outcome }}</u></b>
            
            Репозиторий: ${{ github.repository }}
            
            СсылОчка: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Кстати, если вы это читаете - то Аня жопа а я сделяль телеграм интеграцию :3
