name: Testing project code
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run valid test
        id: test1
        continue-on-error: true
        run: python -m unittest testValid.py
      - name: Run min test
        id: test2
        continue-on-error: true
        run: python -m unittest testMin.py
      - name: Run max test
        id: test3
        continue-on-error: true
        run: python -m unittest testMax.py
      - name: Run sum test
        id: test4
        continue-on-error: true
        run: python -m unittest testSum.py
      - name: Run multiply test
        id: test5
        continue-on-error: true
        run: python -m unittest testMultiply.py
      - name: Run speed tests
        id: test6
        continue-on-error: true
        run: python -m unittest speedTests.py
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} внёс изменения в репозиторий:
            Комментарий: ${{ github.event.commits[0].message }}
            
            Результаты тестов:
            1) Тест на корректное считывание: ${{ steps.test1.conclusion }}
            1) Тест на корректное вычисление минимума: ${{ steps.test2.conclusion }}
            1) Тест на корректное вычисление максимума: ${{ steps.test3.conclusion }}
            1) Тест на корректное вычисление суммы: ${{ steps.test4.conclusion }}
            1) Тест на корректное вычисление произведения: ${{ steps.test5.conclusion }}
            1) Тесты на скорость: ${{ steps.test6.conclusion }}
            
            Репозиторий: ${{ github.repository }}
            
            СсылОчка: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Кстати, если вы это читаете - то Аня жопа а я сделяль телеграм интеграцию :3
